# Generated by Django 5.1.6 on 2025-02-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='createat',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='descrition',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='picture',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='title',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='updateAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
