# Generated by Django 5.1.6 on 2025-02-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marque', '0002_mark_createat_alter_mark_descrition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
