# Generated by Django 5.1.6 on 2025-02-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('idCategory', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, null=True)),
                ('descrition', models.CharField(max_length=200, null=True)),
                ('createat', models.DateTimeField(auto_now_add=True, null=True)),
                ('updateAt', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
